# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rails-ogone 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rails-ogone"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dave Lens"]
  s.date = "2014-10-16"
  s.description = "Rails gem to facilitate simple payments with Ogone."
  s.email = "github@davelens.be"
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "LICENSE",
    "VERSION",
    "lib/generators/ogone/config_generator.rb",
    "lib/generators/ogone/templates/ogone.rb",
    "lib/generators/ogone/templates/ogone.yml",
    "lib/rails-ogone.rb",
    "lib/rails-ogone/form.rb",
    "lib/rails-ogone/hash.rb",
    "lib/rails-ogone/helper.rb",
    "spec/lib/blimp_ogone/form_spec.rb",
    "spec/lib/blimp_ogone/hash_spec.rb"
  ]
  s.homepage = "https://github.com/davelens/rails-ogone"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Rails gem to facilitate simple payments with Ogone."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency 'activesupport'
      s.add_runtime_dependency 'actionview'
      s.add_development_dependency 'rspec'
      s.add_development_dependency 'rspec-mocks'
      s.add_development_dependency 'rdoc'
      s.add_development_dependency 'bundler'
      s.add_development_dependency 'jeweler'
    else
      s.add_dependency 'activesupport'
      s.add_dependency 'actionview'
      s.add_dependency 'rspec'
      s.add_dependency 'rspec-mocks'
      s.add_dependency 'rdoc'
      s.add_dependency 'bundler'
      s.add_dependency 'jeweler'
    end
  else
    s.add_dependency 'activesupport'
    s.add_dependency 'actionview'
    s.add_dependency 'rspec'
    s.add_dependency 'rspec-mocks'
    s.add_dependency 'rdoc'
    s.add_dependency 'bundler'
    s.add_dependency 'jeweler'
  end
end
