# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rails-ogone 0.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rails-ogone"
  s.version = File.read('VERSION').strip

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dave Lens"]
  s.date = "2017-09-20"
  s.description = "Rails gem to facilitate simple payments with Ogone."
  s.email = "github@davelens.be"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/generators/ogone/config_generator.rb",
    "lib/generators/ogone/templates/ogone.rb",
    "lib/generators/ogone/templates/ogone.yml",
    "lib/rails-ogone.rb",
    "lib/rails-ogone/form.rb",
    "lib/rails-ogone/hash.rb",
    "lib/rails-ogone/helper.rb",
    "rails-ogone.gemspec",
    "spec/lib/rails-ogone/form_spec.rb",
    "spec/lib/rails-ogone/hash_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/davelens/rails-ogone"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Ogone functionality for Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.6"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 3.6"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 3.6"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

